In [1]:
# This differs from other analyses that compare  x  to  y , since  x  is not really a variable. 
# For example, if I measure the boiling point of water with 1%, 3%, 5% and 7% salt solutions, I should be able to predict the 
# boiling point at 4%. But with time series, we can't go back and "plug in" a new value of  x , since we can never go back in time. 
# For this reason, a time series with one  y  variable is called univariate.

In [2]:
import datetime

In [5]:
# When no time data is provided, minimum values are used:

year = 2023
month = 9
day = 11

d = datetime.datetime(year,month,day)
print(d)
type(d)

2023-09-11 00:00:00


datetime.datetime

In [6]:
print("date ->", d.date())
print("day ->", d.day)
print("hour ->", d.hour)
print("minute ->", d.minute)
print("second ->", d.second)
print("weekday -> " ,d.weekday()) # returns the day of the week as an integer, where Monday is 0 and Sunday is 6
print("weekday -> " ,d.isoweekday())  #returns the day of the week as an integer, where Monday is 1 and Sunday is 7

date -> 2023-09-11
day -> 11
hour -> 0
minute -> 0
second -> 0
weekday ->  0
weekday ->  1


In [7]:
from datetime import datetime,date,time

#Comparison between datetime and date
print("date --> ",date.today())  # only return the date
print("datetime --> ",datetime.today()) #return date with time

date -->  2023-09-11
datetime -->  2023-09-11 22:43:21.232697


In [24]:
#Time tuples
s = datetime(2004,10,27,20,25,55)
s.timetuple()

time.struct_time(tm_year=2004, tm_mon=10, tm_mday=27, tm_hour=20, tm_min=25, tm_sec=55, tm_wday=2, tm_yday=301, tm_isdst=-1)

## NUMPY

In [8]:
import numpy as np

In [30]:
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [28]:
print(np.zeros(3))
np.zeros((5,5))

[0. 0. 0.]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
print(np.ones(3))
np.ones((3,3))

[1. 1. 1.]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [35]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [17]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(100)

array([0.29314624, 0.56514193, 0.54458141, 0.71753767, 0.86442941,
       0.91948812, 0.72146234, 0.47552358, 0.5728444 , 0.35193496,
       0.22475977, 0.63078874, 0.46842367, 0.35463841, 0.0787935 ,
       0.46483132, 0.09945766, 0.19076505, 0.40527965, 0.99880227,
       0.56762351, 0.8487976 , 0.15402267, 0.33224169, 0.93385297,
       0.55057791, 0.32004544, 0.77208952, 0.6903757 , 0.51035529,
       0.85378282, 0.39251892, 0.33314571, 0.72768356, 0.723938  ,
       0.72749918, 0.86839792, 0.80749336, 0.55963613, 0.5594567 ,
       0.42528386, 0.6767454 , 0.53555535, 0.51472828, 0.06068387,
       0.16139045, 0.04172744, 0.09492397, 0.07346174, 0.9400659 ,
       0.50183789, 0.50573902, 0.5946553 , 0.95658   , 0.57982645,
       0.81091038, 0.03226345, 0.335845  , 0.80930834, 0.5139201 ,
       0.50342332, 0.84254993, 0.64383063, 0.14321132, 0.14239831,
       0.88889156, 0.57285276, 0.18070987, 0.79931217, 0.27009731,
       0.44969419, 0.56337437, 0.43936125, 0.06610222, 0.25916

In [38]:
np.random.rand(5,5)

array([[0.88538375, 0.24491173, 0.9500034 , 0.88975632, 0.69862069],
       [0.78094096, 0.86013771, 0.42406789, 0.42180908, 0.25760474],
       [0.38582754, 0.17783947, 0.89312631, 0.15581296, 0.08234044],
       [0.36570437, 0.63539574, 0.79091825, 0.08070348, 0.52342611],
       [0.12322874, 0.1969906 , 0.62081277, 0.11207026, 0.14251672]])

In [19]:
# Returns a sample from the "standard normal" distribution [σ = 1]. Unlike rand which is uniform, values closer to zero 
np.random.randn(10)

array([ 2.33424781e-01, -1.58871558e+00, -1.09607913e-03, -1.16153818e+00,
       -6.29542807e-01,  6.53994114e-01,  1.41000384e+00, -1.88395950e-01,
       -5.72606810e-01, -2.47469039e-01])

In [41]:
np.random.randn(5,5)

array([[-0.75179093, -0.09281269, -0.18831568, -0.36511379, -0.82520334],
       [-0.56130243, -0.14493589,  1.37105099, -0.32731118, -0.05921311],
       [-0.53249149, -1.23470539, -0.61236025,  0.79319803,  0.01461461],
       [-0.5299107 ,  1.78439949, -0.83872101,  0.24200005,  0.89323991],
       [ 0.42080219, -1.42131226,  1.26368257,  0.2640065 ,  0.47002055]])

In [36]:
np.random.seed(42)
np.random.randint(1,20,10)

array([ 7, 15, 11,  8,  7, 19, 11, 11,  4,  8])

In [35]:
# Can be used to set the random state, so that the same "random" results can be reproduced
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [51]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arr = np.arange(25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
print("Max -> ", arr.max())
print("Max -> ", arr.argmax()) # used for finding the index location
print("Min -> ", arr.min())
print("Max -> ", arr.argmin())  # used for finding the index location

Max ->  24
Max ->  24
Min ->  0
Max ->  0


In [43]:
arr.shape

(25,)

In [56]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [57]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [46]:
#slicing
print(arr[2])
print(arr[2:5])

3
[3, 2, 5]


In [54]:
arr[2:5]=10
arr

array([ 0,  1, 10, 10, 10,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [64]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [66]:
print(arr_2d[1])
print(arr_2d[1][0])
print(arr_2d[1,1])

[20 25 30]
20
25


In [67]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [71]:
bool_arr = arr > 15
bool_arr

array([False, False,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [72]:
arr[bool_arr]

array([100, 100, 100,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [73]:
#Operations
arr = np.arange(0,10)
print(arr)
print(arr + arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [74]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [75]:
# Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [76]:
# Calculating exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [77]:
# Trigonometric Functions like sine
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [78]:
# Taking the Natural Logarithm
np.log(arr)

C:\Users\arsha\AppData\Local\Temp\ipykernel_23136\2367246271.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [91]:
#Statistical operations
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())

print("varience -> ", arr.var())
print("S.D. -> ",arr.std())

45
4.5
9
0
varience ->  8.25
S.D. ->  2.8722813232690143


In [92]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
#By passing in axis=0, we're returning an array of sums along the vertical axis, essentially [(1+5+9), (2+6+10), (3+7+11), (4+8+12)]
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [95]:
#By passing in axis=1, we're returning an array of sums along the horizontal axis
arr_2d.sum(axis=1)

array([10, 26, 42])